In [71]:
import pandas as pd
import os
from joblib import dump

base_path : str = os.path.dirname(os.getcwd())
csv_path  : str = base_path + '\\csv'
src_path  : str = base_path + '\\src'
json_path : str = base_path + '\\json'

def distance_set(list1, list2) -> float:
    return 1.0 - len(set(list1)&set(list2))/len(set(list1)|set(list2))

movies = pd.read_csv(csv_path + "\\MOVIES_DATA.csv", sep=',').drop('Unnamed: 0', axis=1)

In [60]:
movies

,MOVIE_ID,TITLE,TMDB_ID,title,director,production_companies,genres,popularity,rating,actors,overview
0,1,12 Angry Men,389,12 Angry Men,['Sidney Lumet'],"['United Artists', 'Orion-Nova Productions']",['Drama'],70.722,8.545,"['Lee J. Cobb', 'Henry Fonda', 'Martin Balsam'...",The defense and the prosecution have rested an...
1,2,2001: A Space Odyssey,62,2001: A Space Odyssey,['Stanley Kubrick'],"['Kubrick Productions', 'Metro-Goldwyn-Mayer']","['Science Fiction', 'Mystery', 'Adventure']",77.925,8.073,"['Stanley Kubrick', 'Keir Dullea', 'Gary Lockw...",Humanity finds a mysterious object buried bene...
2,3,3 Idiots,20453,3 Idiots,['Rajkumar Hirani'],"['Vidhu Vinod Chopra Productions', 'Vinod Chop...","['Drama', 'Comedy']",30.586,8.000,"['Kareena Kapoor Khan', 'Aamir Khan', 'Ali Faz...",Rascal. Joker. Dreamer. Genius... You've never...
3,4,A Beautiful Mind,453,A Beautiful Mind,['Ron Howard'],"['Universal Pictures', 'DreamWorks Pictures', ...","['Drama', 'Romance']",49.376,7.900,"['Russell Crowe', 'Jennifer Connelly', 'Bryce ...","Brilliant mathematician, John Nash, is on the ..."
4,5,A Clockwork Orange,185,A Clockwork Orange,['Stanley Kubrick'],"['Warner Bros. Pictures', 'Hawk Films', 'Kubri...","['Science Fiction', 'Crime']",63.517,8.200,"['Malcolm McDowell', 'Gillian Hills', 'Adrienn...","In a near-future Britain, young Alexander DeLa..."
...,...,...,...,...,...,...,...,...,...,...,...
195,196,Tonari no Totoro,8392,My Neighbor Totoro,['宮崎駿'],"['Studio Ghibli', 'Nibariki', 'Tokuma Shoten']","['Fantasy', 'Animation', 'Family']",75.908,8.100,"['中村大樹', '大谷育江', '千葉繁', '坂本千夏', '日髙のり子', '島本須美...",Two sisters move to the country with their fat...
196,197,Touch of Evil,1480,Touch of Evil,['Orson Welles'],['Universal International Pictures'],"['Crime', 'Thriller', 'Mystery']",27.881,7.757,"['Orson Welles', 'Charlton Heston', 'Dennis We...",When a car bomb explodes on the American side ...
197,198,Toy Story,862,Toy Story,['John Lasseter'],['Pixar'],"['Animation', 'Adventure', 'Family', 'Comedy']",122.612,8.000,"['Tom Hanks', 'Annie Potts', 'Wallace Shawn', ...","Led by Woody, Andy's toys live happily in his ..."
198,199,Trainspotting,627,Trainspotting,['Danny Boyle'],"['Figment Films', 'Film4 Productions', 'The No...","['Drama', 'Crime']",41.585,8.000,"['Ewan McGregor', 'Kelly Macdonald', 'Kevin Mc...",Heroin addict Mark Renton stumbles through bad...
199,200,Trois couleurs: Rouge,110,Three Colors: Red,['Krzysztof Kieślowski'],"['MK2 Films', 'France 3 Cinéma', 'CAB Producti...","['Drama', 'Mystery', 'Romance']",23.742,7.900,"['Julie Delpy', 'Juliette Binoche', 'Jean-Loui...",Part-time model Valentine unexpectedly befrien...

In [66]:
movie_keys = []
for i in range(200):
    for j in range(200):
        movie_keys.append(i*200+j)

In [62]:
distance_movies = []
for movie1 in movies["popularity"]:
    for movie2 in movies["popularity"]:
        distance_movies.append([abs(movie1 - movie2)])

for id1, movie1 in enumerate(movies["rating"]):
    for id2, movie2 in enumerate(movies["rating"]):
        distance_movies[id1*len(movies["rating"])+id2].append(abs(movie1 - movie2))


for id1, movie1 in enumerate(movies["director"]):
    for id2, movie2 in enumerate(movies["director"]):
        distance_movies[id1*len(movies["director"])+id2].append(distance_set(eval(movie1),eval(movie2)))


for id1, movie1 in enumerate(movies["actors"]):
    for id2, movie2 in enumerate(movies["actors"]):
        distance_movies[id1*len(movies["actors"])+id2].append(distance_set(eval(movie1),eval(movie2)))

for id1, movie1 in enumerate(movies["genres"]):
    for id2, movie2 in enumerate(movies["genres"]):
        distance_movies[id1*len(movies["genres"])+id2].append(distance_set(eval(movie1),eval(movie2)))

In [73]:
movie_distance_graph = {movie_keys[i]:distance_movies[i] for i in range(len(movie_keys))}
dump(movie_distance_graph, csv_path + "\\movie_distance_graph.joblib")

['d:\\repos\\TUL-Machine-Learning\\csv\\movie_distance_graph.csv']